# Generated by Django 4.2.23 on 2025-08-11 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_fake', models.BooleanField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fake_prediction', models.BooleanField()),
                ('fake_confidence_score', models.FloatField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('compression_ratio', models.FloatField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('sentiment_confidence', models.FloatField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='2.0', max_length=50)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.newsarticle')),
            ],
        ),
    ]
