# Generated by Django 4.2.23 on 2025-10-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysisresult_topic_analysisresult_topic_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='input_source',
            field=models.CharField(choices=[('url', 'URL'), ('text', 'Văn bản'), ('file', 'File')], default='url', max_length=10),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
